### PR TITLE
Support java.util.ArrayList

### PR DESCRIPTION
**Pull request by kgann**
[Fressian](https://github.com/Datomic/fressian) reads and writes vectors as `java.util.ArrayList`. This PR adds support for these objects.

### CODE REVIEW

**Comment by Jarzka** [comment]
Thank you for your PR. I'll take a more in-depth look at it in the coming days.

However, after my quick overview, I just had an idea of implementing support for ArrayList in more generic way. There is already a `coll?` check so that this library could handle all kinds of collection types. However, now I realise it does not support Java types. I guess replacing `coll?` with `seqable?` would handle ArrayList and provide support for other interable Java types at the same time. What do you think?

**Comment by kgann** [comment]
If you used `seqable?` it would also return `true` on other types such as strings:

```clojure
user=> (seqable? "string")
true
user=> (seqable? nil)
true
```

Would this cause issues in other places?

**Comment by Jarzka** [comment]
You are right, it could probably lead to confusing situations since so many types are seqable. Maybe explicit support for ArrayList is better.

**Comment by kgann** [comment]
> Maybe explicit support for ArrayList is better.

I'd love to be able to support other types in a more generic way but I couldn't land on a good solution.

**Comment by Jarzka** [comment]
Luckily adding explicit support for Java ArrayList does not prevent us from adding generic support for other collection types later, if needed. :)

By the way, did you try to compile ClojureScript build? This library is designed to support both Clojure and ClojureScript. The tests are run only in Clojure/JVM right now, which is a bit unfortunate.

**Comment by kgann** [comment]
Good call. See 370c6925795122b39dd0e39371632a5cf654d19e

**Comment by Jarzka** [comment]
Great, thanks! As I said, I'll take a more in-depth look at this PR in the coming days. Have a nice weekend!

**Comment by kgann** [comment]
See e3a7e8c13bda56a4d368722f64aa5db7936cad34 as well so we can support anything implementing `java.util.Collection`.

**Comment by Jarzka** [comment]
Looks good. I will merge this and release it.

One minor thing though: in`core_test.clj` on line 150 we namespacefy a vector of two vectors, then on line 160 we assume that the end results contains a vector of one vector and one Java ArrayList instead of vector. To me, this sounds a bit confusing, since it feels like that in the end result one vector has changed its type to Java ArrayList. The test still passes though since `=` does not require the same collection types, which is fine.

However, I think this test would be more clear if we change it vice versa: If the input vector contains a vector and a Java ArrayList, then we assume that if we namespacefy it, the end result is comparable with a vector of two vectors. I can make this change by myself after merge.

**Pull request merged**
